Sub prueba()

    documento
    
End Sub

' Obtener documento especifico
Sub documento()

    ' Abrir documento en la ruta especificada
    Dim documento As Inventor.Document
    Set documento = ThisApplication.Documents.Open("C:\Users\cesar\Downloads\Reductor de Velocidad-20170408T222446Z-001\Reductor de Velocidad\Modelo\1 Reductor.iam", True)
    Debug.Print "Document: " + documento.FullFileName
    
    conjuntosDePropiedades documento

End Sub

' Obtener conjuntos de propiedades
Sub conjuntosDePropiedades(documento As Inventor.Document)

    ' Obtener conjuntos de propiedades
    Dim conjuntosDePropiedades As PropertySets
    Set conjuntosDePropiedades = documento.PropertySets
    Debug.Print "   PropertySets: " + CStr(conjuntosDePropiedades.Count)
    
    conjuntoDePropiedades conjuntosDePropiedades
    
    

End Sub

' Obtener conjunto de propiedades
Sub conjuntoDePropiedades(conjuntosDePropiedades As PropertySets)

    Dim i As Integer
    For i = 1 To conjuntosDePropiedades.Count
 
        ' Obtener conjunto de propiedades de los conjuntos de propiedades
        Dim conjuntoDePropiedades As PropertySet
        Set conjuntoDePropiedades = conjuntosDePropiedades.Item(i)
        
        ' Mostrar nombre del conjunto de propiedades en consola
        Debug.Print "       PropertySet: " + conjuntoDePropiedades.Name
        
        propiedad conjuntoDePropiedades
    
     Next

End Sub

' Obtener propiedad
Sub propiedad(conjuntoDePropiedades As PropertySet)

    Dim i As Integer
    For i = 1 To conjuntoDePropiedades.Count
 
        ' Obtener propiedad del conjunto de propiedades
        Dim propiedad As Property
        Set propiedad = conjuntoDePropiedades.Item(i)
        
        ' Mostrar nombre del conjunto de propiedades en consola
        Debug.Print "           Property: " + propiedad.Name
    
     Next

End Sub


