
Sub prueba()

    ' Abrir documento de enamblaje en la ruta especificada
    Dim docInventor As Inventor.AssemblyDocument
    Set docInventor = ThisApplication.Documents.Open("C:\Users\cesar\Downloads\Reductor de Velocidad-20170408T222446Z-001\Reductor de Velocidad\Modelo\1 Reductor.iam", True)
    Debug.Print "PartDocument: " + docInventor.File.FullFileName
    
    ' crear asset
    Dim localAsset As asset
    On Error Resume Next
    
    ' Especificar nombre del material
    Set localAsset = docInventor.Assets.Item("White Ash - Java")
    If Err Then
        On Error GoTo 0
        
        ' Si no se encuentra se accede a la libreria de assets
        Dim assetLib As AssetLibrary
        Set assetLib = ThisApplication.AssetLibraries.Item("Autodesk Appearance Library")
        
        ' Especificar nombre del material
        Set libAsset = assetLib.AppearanceAssets.Item("White Ash - Java")
        
        ' Copiar el asset de la libreria al asset local
        Set localAsset = libAsset.CopyTo(docInventor)
    End If
    On Error GoTo 0
           
    ' Crear una occurrencia de componente seleccionado por el usuario
    Dim occ As ComponentOccurrence
    Set occ = ThisApplication.CommandManager.Pick(kAssemblyOccurrenceFilter, "Select an occurrence.")
    
    ' Asignar el asset al objeto seleccionado
    occ.Appearance = localAsset
    
End Sub