
Sub prueba()

    Dim nombreAsset As String
    nombreAsset = "With Stone 1"
    
    Dim direccion As String
    direccion = "C:\Users\cesar\Downloads\Reductor de Velocidad-20170408T222446Z-001\Reductor de Velocidad\Modelo\1.1 Carcaza Inferior.ipt"
    
    ' Abrir documento de enamblaje en la ruta especificada
    Dim docInventor As Inventor.PartDocument
    Set docInventor = ThisApplication.Documents.Open(direccion, True)
    Debug.Print "PartDocument: " + docInventor.File.FullFileName
    
    ' crear asset
    Dim localAsset As asset
    On Error Resume Next
    
    ' Especificar nombre del material
    Set localAsset = docInventor.Assets.Item(nombreAsset)
    If Err Then
        On Error GoTo 0
        
        ' Si no se encuentra se accede a la libreria de assets
        Dim assetLib As AssetLibrary
        Set assetLib = ThisApplication.AssetLibraries.Item("Autodesk Appearance Library")
        
        ' Especificar nombre del material
        Set libAsset = assetLib.AppearanceAssets.Item(nombreAsset)
        
        ' Copiar el asset de la libreria al asset local
        Set localAsset = libAsset.CopyTo(docInventor)
    End If
    On Error GoTo 0
    
    Dim i As Integer
    For i = 1 To docInventor.ComponentDefinition.Features.Count
    
        ' Obtener caracteristicas
        Dim caracteristica As PartFeature
        Set caracteristica = docInventor.ComponentDefinition.Features.Item(i)
        
        caracteristica.Appearance = localAsset
        
        Debug.Print caracteristica.Name
    
     Next
        
End Sub



